import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';

import Layout from '@components/Layout';
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Time to learn TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-col max-w-7xl mx-auto min-h-screen item-center justify-center">
          <Image src="/ts-logo.svg" alt="ts" width={200} height={200} />
          <h1 className="text-black text-5xl font-bold text-center mt-5 ">Learn Typescript</h1>
          <p className="text-center mt-2">Is time to learn it</p>
        </div>
      </Layout>
    </div>
  );
};

export default Home;
