import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';
import Button from '@components/Button';
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Time to learn TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col max-w-7xl mx-auto min-h-screen item-center justify-center">
        <h1 className="text-black text-5xl font-bold text-center mb-10">Learn Typescript</h1>
        <Image src="/ts-logo.svg" alt="ts" width={200} height={200} />
        <div className="max-w-sm mx-auto mt-5 flex">
          <Button route="/basics/01-basics" title="01-Basics" />
          <Button route="/basics/02-functions" title="02-Functions" />
        </div>
      </div>
    </div>
  );
};

export default Home;
